# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_artist', models.CharField(max_length=200)),
                ('song_text', models.CharField(max_length=200)),
                ('cities', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Song'),
        ),
    ]
