# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170705_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesInSong',
            fields=[
                ('city', models.CharField(db_column='city', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_cities',
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(db_column='songId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_artist',
            field=models.CharField(db_column='songArtist', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(db_column='songName', max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_text',
            field=models.CharField(db_column='songText', max_length=1000),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='citiesinsong',
            name='song_id',
            field=models.ForeignKey(db_column='songId', on_delete=django.db.models.deletion.CASCADE, to='polls.Song'),
        ),
    ]
